# Generated by Django 4.0.3 on 2022-03-08 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_founders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Founders',
            new_name='Founder',
        ),
    ]
