# Generated by Django 4.0.3 on 2022-03-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('city', models.CharField(default=False, max_length=100)),
                ('state', models.CharField(default=False, max_length=100)),
                ('occupation', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('statement', models.CharField(max_length=3000)),
                ('education', models.CharField(max_length=3000)),
                ('address', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
