# Generated by Django 4.0.3 on 2022-03-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_founders_founder'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='state',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
